### DISCUSSION TITLE
QSV with Intel Arc GPUs

### DISCUSSION THREAD

**Discussion by proud-nerd** [automatic-ripping-machine/automatic-ripping-machine#1391] [Show and tell]
# What I wanted to accomplish

I have an Intel Arc A380 and wanted to use that for transcoding with arm like forever. It should in theory speed up transcoding by A LOT and I could even tinker around with AV1.

# The Problem(s)

There is some [documentation for adding QSV support](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Hardware-Transcode-Intel-QSV), that suggests using the [ubuntu-quicksync.sh](https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/main/scripts/installers/ubuntu-quicksync.sh) script, but that is for QSV support with CPUs. Took me more time to realize, than I'd like to admit.

There are some issues and discussions, where people got it to work ([1](https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/909), [2](https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/1248), [3](https://github.com/automatic-ripping-machine/automatic-ripping-machine/discussions/1120), [4](https://github.com/automatic-ripping-machine/automatic-ripping-machine/discussions/1185)).  But there does not seem to be an issue or discussion that explicitly aims for Intel Arc GPUs. Also, those were either only for QSV with CPU or I could not replicate their success (could very well be a fault on my part).

Another problem: Most guides or posts installed [Intels MediaSDK](https://github.com/Intel-Media-SDK/MediaSDK), but a) it's discontinued since May 17, 2023 and b) it does not even support Intel Arc Cards as u can see in [this table](https://github.com/intel/libvpl?tab=readme-ov-file#dispatcher-behavior-when-targeting-intel-gpus).

Third problem: Intels documentation, what you need to install to get their card working for transcoding is kinda lack luster and all over the place. There is pretty good build documentation for each of their software tools and libraries, though.

# How I got it to work

## Requirements

- A working arm environment running in docker. If you are not running docker, it should be possible to execute the commands from the Dockerfile directly in ubuntu, but steps or packages might differ if you are not using ubuntu 22.04.
- An Intel Arc Card, I'm using Arc A380, but others should also work
- The system docker is running on should have drivers installed for your Intel Arc. I set this up quite some time ago and do not remember what was necessary for this, but I think on Ubuntu 24.04. I did not need to do anything and drivers should be included since kernel 6.2. But [here](https://dgpu-docs.intel.com/driver/client/overview.html#ubuntu-24.10-24.04) are some instructions from Intel, just in case.

## docker image

These are the steps to prepare the docker image:

1. Install Intel Arc drivers for Ubuntu 22.04: https://dgpu-docs.intel.com/driver/client/overview.html#ubuntu-22.04
2. Install oneAPI Base Toolkit: https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?packages=oneapi-toolkit&oneapi-toolkit-os=linux&oneapi-lin=apt
3. Build & install latest [libva](https://github.com/intel/libva)
4. Build & install [gmmlib](https://github.com/intel/gmmlib) as a dependency for Intel Media Driver
5. Build & install [Intel Media Driver for VAAPI](https://github.com/intel/media-driver)
6. Install [Intel VPL](https://github.com/intel/libvpl) & [Intel VPU GPU runtime](https://github.com/intel/vpl-gpu-rt)

For easy of usage, here is my Dockerfile. Feel free, to change the image tag to latest. Building that can take quite some time, depending on your hardware. You have been warned.

**Sidenote**: If you create a `.env`-File next to your `docker-compose.yml` and put `COMPOSE_BAKE=true` in there, the build process should be quite a bit faster.

```
FROM automaticrippingmachine/automatic-ripping-machine:2.13.0
LABEL desc="ARM w/ Intel Quick Sync Video Support"
RUN apt update -y && apt upgrade -y

# install drivers for intel arc for ubuntu 22.04
# https://dgpu-docs.intel.com/driver/client/overview.html#ubuntu-22.04
RUN wget -qO - https://repositories.intel.com/gpu/intel-graphics.key | gpg --yes --dearmor --output /usr/share/keyrings/intel->
    echo "deb [arch=amd64,i386 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu jam>
    apt update &&\
    apt install -y libze-intel-gpu1 libze1 intel-opencl-icd clinfo intel-gpu-tools

# build latest libva
# https://github.com/intel/libva?tab=readme-ov-file#build-and-install-libva
RUN apt install -y libmfx1 libmfx-tools libmfx-dev vorbis-tools wget libva-dev libdrm-dev &&\
    mkdir -p quicksync && cd quicksync &&\
    git clone https://github.com/intel/libva.git libva &&\
    cd libva &&\
    ./autogen.sh &&\
    make && make install &&\
    rm -rf quicksync

# install oneAPI Base Toolkit
# https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?packages=oneapi-toolkit&oneapi-too>
RUN apt install -y gpg-agent wget &&\
    wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | tee /usr/share/key>
    echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | tee /e>
    apt update -y &&\
    apt install -y intel-oneapi-base-toolkit &&\
    apt install -y cmake pkg-config build-essential

# build gmmlib
# https://github.com/intel/gmmlib?tab=readme-ov-file#building
RUN git clone https://github.com/intel/gmmlib.git &&\
    cd gmmlib &&\
    mkdir build && cd build &&\
    cmake -DCMAKE_BUILD_TYPE=Release -DARCH=64 -DRUN_TEST_SUITE=OFF .. &&\
    make -j"$(nproc)" &&\
    make install

# build media-driver
# https://github.com/intel/media-driver?tab=readme-ov-file#building
RUN apt install -y autoconf libtool libdrm-dev xorg xorg-dev openbox libx11-dev libgl1-mesa-glx &&\
    git clone https://github.com/intel/media-driver.git media-driver &&\
    mkdir build_media && cd build_media &&\
    cmake ../media-driver -DENABLE_KERNELS=ON -DENABLE_NONFREE_KERNELS=ON -DENABLE_PRODUCTION_KMD=ON  &&\
    make -j"$(nproc)" &&\
    make install

# install Intel VPL and VPL GPU runtime
RUN apt install -y libvpl2 libvpl-dev libmfx-gen1.2
```

## docker-compose

1. use custom docker image instead of the prebuild one. Place the above code into a file called `Dockerfile` and reference the path where to find it
2. set `privileged: true`
3. the user that is running arm inside of the container (`arm` for me) needs to be in the video and render group outside of the container (run `usermod -a -G render arm` and `usermod -a -G video arm`)
4. add your GPU to devices (for me /dev/dri/renderD128, but name might differ for you). You also need to add the corresponding path to card (for me /dev/dri/card1, but might be different for you). You can check by installing `intel-gpu-tools` and run `intel_gpu_top`, it will show you the correct path in the first line of the output.

For reference, here is my docker-compose.yaml:

```
services:
  arm:
    container_name: arm
    build:
      context: ./arm-qsv <-- step 1
    restart: unless-stopped
    privileged: true <-- step 2
    environment:
      - TZ=Europe/Berlin
      - ARM_UID=110 <-- step 3
      - ARM_GID=110
      - AUTH_TYPE=Basic
    volumes:
      - ./home/config:/etc/arm/config
      - ./home/logs:/home/arm/logs
      - ./home:/home/arm
      - ./workingdir/media:/home/arm/media
      - truenas-media-completed:/home/arm/media/completed
      - truenas-music-completed:/home/arm/music
      - ./makemkv/makemkvsettings.xml:/opt/arm/makemkvsettings.xml
    devices:
      - /dev/sr0
      - /dev/sg2
      - /dev/sr1
      - /dev/sg3
      - /dev/dri/renderD128 <-- step 4
#      - /dev/dri/card0
      - /dev/dri/card1 <-- step 4
    ports:
      - 8086:8080
    healthcheck:
      test: curl --fail http://arm:8080 || exit 1
      interval: 60s
      retries: 2
      start_period: 20s
      timeout: 10s
```

## Validation

At this point, QSV support should work. You can check by opening a shell in the container (`docker compose exec -it arm /bin/bash`) and then execute `HandBrakeCLI --help | grep -A12 "Select video encoder"`. The output should include some options starting with `qsv_`.

## Arm configuration

Follow the [official documentation for QSV](https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Hardware-Transcode-Intel-QSV) for that one. You basically need to set `HB_PRESET_DVD` and/or `HD_PRESET_BD` in Ripper Settings to a QSV profile. You can run `docker compose exec -it arm /bin/bash` to start a shell inside of the arm docker container and execute `HandBrakeCLI -z` to see a list of available presets.

# Final words

Huge thanks to everyone who contributed to all those conversations about QSV. I'm no expert and basically threw everything together from those issues and discussions + some reddit posts and this [gist](https://gist.github.com/FarisR99/84e3e5f2e564b0dc7921e3186dbefd15) from @FarisR99.

This Dockerfile does work for me, but I'm not entirely sure, if all of those steps are necessary or if some of them can be skipped. I will continue to tinker around with it, but building the docker image takes quite some time so I thought I'd save that for another day.

Every hint for other or unneeded dependencies is very welcome.
I hope this helps anyone and I will try to keep this post up to date.
