### ISSUE TITLE
🐛 Docker Syslog Severity

### ISSUE THREAD

**Issue by bioszombie** [automatic-ripping-machine/automatic-ripping-machine#1012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

![Screenshot 2023-12-14 at 10 30 18 AM](https://github.com/automatic-ripping-machine/automatic-ripping-machine/assets/77448489/154f2afc-e35c-43ed-abe9-b1842b480560)

[2023-12-14 14:52:00,283] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f53dbdc5fa0>) (save_remote_images=True) (language=en) (id=1) (database_limit=200) (bootstrap_skin=spacelab) (use_icons=True) (index_refresh=2000) (notify_refresh=6500) 

Debug severity are output as error severity in the syslog.

### To Reproduce

docker-compose.yml
```
name: automaticrippingmachine
services:
    automatic-ripping-machine:
        ports:
            - 8080:8080
        environment:
            TZ: "UTC"
            ARM_UID: "1001"
            ARM_GID: "1001"
        volumes:
            - /home/arm:/home/arm
            - /home/arm/Music:/home/arm/Music
            - /home/arm/logs:/home/arm/logs
            - /home/arm/media:/home/arm/media
            - /home/arm/config:/etc/arm/config
        devices:
            - /dev/sr0:/dev/sr0
            - /dev/sr1:/dev/sr1
            - /dev/sr2:/dev/sr2
            - /dev/sr3:/dev/sr3
        privileged: true
        restart: always
        container_name: arm-rippers
        image: automaticrippingmachine/automatic-ripping-machine
```

```
docker compose up -d
```

### What OS are you seeing the problem on?

Debian 11

### ARM Release Version or Git hash (You can find this in the arm settings page)

ecbba569b20d61f455c47669dc96657ae8756455

### Expected behavior?

Debug messages should appear as numerical code 7 or Severity Debug.

### Relevant log output

```shell
[2023-12-14 14:52:00,283] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f53dbdc5fa0>) (save_remote_images=True) (language=en) (id=1) (database_limit=200) (bootstrap_skin=spacelab) (use_icons=True) (index_refresh=2000) (notify_refresh=6500) 

[2023-12-14 14:52:00,283] DEBUG ARM: utils.arm_db_check Database is current. Head: 469d88477c13DB: 469d88477c13

[2023-12-14 14:52:00,283] DEBUG ARM: utils.arm_db_get Database Head is: 469d88477c13
```

### Anything else?

Is there a way to edit the severity of the log output via the compose file and or disable debug log output?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
