### ISSUE TITLE
Docker Startup error

### ISSUE THREAD

**Issue by Bestest-Coder** [automatic-ripping-machine/automatic-ripping-machine#1019]
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/20e3ac86b7a84870d7f23a60921c91468edca063/scripts/docker/runit/arm_user_files_setup.sh#L70C4-L70C4

I think this line needs to be either `-rf` or check that `/home/arm/music` exists, because it currently fails as `rm -f` does not work on directories and cannot be worked around by directly making a volume at `/home/arm/Music`

**Comment by pweinrich3** [comment]
Having the same issue. Tested on a brand new Ubuntu 20.04 VM with the latest updates and followed the wiki instructions. Receiving this error: 

```
Dec 22 23:34:17 2b53d3cb5526 syslog-ng[11]: syslog-ng shutting down; version='3.25.1'
*** Running /etc/my_init.d/10_syslog-ng.init...
Dec 22 23:34:18 2b53d3cb5526 syslog-ng[11]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm group id 1000 to default (1000)...
usermod: no changes
Updating arm group id 1000 to default (1000)...
Adding arm user to 'render' group
rm: cannot remove '/home/arm/music': Is a directory
*** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
```

**Comment by sdight** [comment]
I changed line 70 of to rm -rf and it solved the issue.

**Comment by Poweruser7** [comment]
@sdight how did you do that? I assume you built de image locally. Or is there a easier way?

**Comment by microtechno9000** [comment]
Replicated the issue, and changing the rm to an rm -rf solves the issue

**Comment by speedythesnail** [comment]
I can't wait for #1025 to be merged, thanks for the work! 

I just discovered ARM this week and immediate ran into this issue. 

@Poweruser7 
I resolved this issue by editing the script and mounting it as a volume in my docker-compose file, rather than building a new image:
You can just pass it as an option to docker if you don't want to use compose, but I prefer compose over a docker run command.

Sample of my docker-compose.yaml file:
```
version: '3.8'
services:
  arm-rippers:
    image: automaticrippingmachine/automatic-ripping-machine:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      ARM_UID: 1001
      ARM_GID: 1002
    volumes:
      - '/media/arm/home:/home/arm'
      - '/media/arm/etc-config:/etc/arm/config'
      - '/media/arm/arm_user_files_setup.sh:/etc/my_init.d/arm_user_files_setup.sh'
    cpuset: '0,1,2,3,4,5'
```

Sometime this year I'd love to contribute to this project, I'll probably provide a sample Docker compose file that supports HTTPS with either your own certificate, or LetsEncrypt, using jwilder's nginx reverse proxy.
