### ISSUE TITLE
🐋 <Running Docker Container As Non-Root>

### ISSUE THREAD

**Issue by polskikrol** [automatic-ripping-machine/automatic-ripping-machine#1074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When I attempt to run a container with the UID and GID of the arm user on the docker host, I receive errors.

Here is the addition to my docker-compose.yml file --- user: '1002:1003'.

Here is the error:

```
PermissionError: [Errno 13] Permission denied: '/etc/container_environment'
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 414, in <module>
    main(args)
  File "/sbin/my_init", line 330, in main
    import_envvars(False, False)
  File "/sbin/my_init", line 90, in import_envvars
    for envfile in listdir("/etc/container_environment"):
  File "/sbin/my_init", line 74, in listdir
    return sorted(os.listdir(path))
```

I have the docker image running perfect as the root user with Intel QSV acceleration, however, trying to see if its possible to run this in a more secure manner.

### To Reproduce

See description.

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

Should be able to run as a non-root user.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
What are the permissions for the mounted volumes?

**Comment by polskikrol** [comment]
> What are the permissions for the mounted volumes?

There are all owned by the host user 'arm' part of group 'arm'. I used these respective UID and GID to pass into the container. The actual files shared as volumes were chown arm:arm recursively, including the hidden files.

Here is the docker file that works. When I try to uncomment the user statement, it breaks with the error mentioned in the original post.

```
version: '3.8'
services:
  arm:
    image: 'arm/arm-qsv:latest'
    container_name: 'arm'
    hostname: 'arm'
    networks:
      docker_bridge:
        ipv4_address: '172.16.0.3'
#    user: '1002:1003' 
#    group_add:
#      - '109' # host render group id
    environment:
      - ARM_UID=1002
      - ARM_GID=1003
      - TZ=America/New_York
    volumes:
      - /docker/arm/files/arm:/home/arm
      - /docker/arm/files/logs:/home/arm/logs
      - /docker/arm/files/media:/home/arm/media
      - /docker/arm/files/music:/home/arm/music
      - /docker/arm/files/config:/etc/arm/config
    devices:
      - /dev/sr0:/dev/sr0 
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - '8080:8080' # port for web interface
    privileged: true
    restart: 'unless-stopped'
    build:
      context: '/docker/arm'
      dockerfile: 'dockerfile' 
networks:
  docker_bridge:
    external: true
```
Using a custom build which only installs the required tools and compiles the code needed to enable Intel Quicksync. Not other modifications to any scripts or anything. Using current tag docker image.
