### ISSUE TITLE
🐋 Container is stuck in status "health: starting" when running inside an ipv6 network

### ISSUE THREAD

**Issue by cryptogeek13** [automatic-ripping-machine/automatic-ripping-machine#1170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When I start the container in an ipv6 enabled docker network, it's stuck in `health: starting`. A.R.M. is starting normally as far as I can tell and the UI is accessible though.

I stumbled across this because I'm running arm behind a traefik reverse proxy (for internal network only), so the proxy network from the provided example compose file is an external network in my case. I need the container to be on that network so traefik can reach it. This is a problem because traefik only starts to pick up containers once they are in health status `running`.

I also noticed that inside the container the binding on port `8080` is not on `localhost` but on the ip on the docker network (for example `172.29.0.2`). Could that be related? That stopped me from just setting a custom healthcheck inside of my docker compose file, because I can't simply curl localhost.

### To Reproduce

```
services:
  arm:
    container_name: arm
    image: automaticrippingmachine/automatic-ripping-machine:2.7.2
    restart: unless-stopped
    privileged: true
    environment:
      - ARM_UID=110
      - ARM_GID=110
      - AUTH_TYPE=Basic
    devices:
      - /dev/sr0:/dev/sr0
    ports:
      - 8080:8080
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    enable_ipv6: true
```

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

The container should leave status `starting` and enter status `running`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by microtechno9000** [comment]
Thanks for trying ARM, can you provide details from the docker logs. Something like `docker logs -f automatic-ripping-machine `, using the name of your ARM container.

Docker uses a network bridge to loop back to the local machine, and some docker network magic. Not having tested ARM or even docker with ipv6, I can't say much on what would happen.
However, provide any logs you do get, as well as the `docker ps` and go from there

**Comment by cryptogeek13** [comment]
As a workaroud you can set a healthcheck, just like you already tried. Instead of using localhost you can use the name of your container, like this:

```
healthcheck:
      test: curl --fail http://arm:8080 || exit 1
      interval: 60s
      retries: 2
      start_period: 20s
      timeout: 10
```
