### ISSUE TITLE
🐋 Starting fails trying to chown folders that are mounted by docker via NFS

### ISSUE THREAD

**Issue by btoconnor** [automatic-ripping-machine/automatic-ripping-machine#1186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Starting the docker container fails with the error:
```
arm-rippers-1  | *** Running /etc/my_init.d/10_syslog-ng.init...
arm-rippers-1  | Sep  1 01:29:21 860e67934750 syslog-ng[12]: syslog-ng starting up; version='3.25.1'
arm-rippers-1  | *** Running /etc/my_init.d/arm_user_files_setup.sh...
arm-rippers-1  | Updating arm user id from 1000 to 1035...
arm-rippers-1  | Updating arm group id from 1000 to 100...
arm-rippers-1  | Adding arm user to 'render' group
arm-rippers-1  | Checking ownership of /home/arm
arm-rippers-1  | ---------------------------------------------
arm-rippers-1  | [ERROR]: ARM does not have permissions to /home/arm using 1035:100
arm-rippers-1  | Check your user permissions and restart ARM. Folder permissions--> 1035:1000
arm-rippers-1  | ---------------------------------------------
arm-rippers-1  | *** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
arm-rippers-1  |
arm-rippers-1  | *** Killing all processes...
arm-rippers-1  | Sep  1 01:29:25 860e67934750 syslog-ng[12]: syslog-ng shutting down; version='3.25.1'
```

### To Reproduce

This is my configuration, with the synology ip redacted:

```yaml
version: "3.4"
services:
  arm-rippers:
    image: automaticrippingmachine/automatic-ripping-machine:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - ./config:/etc/arm/config
      - armdata:/home/arm/media
      - arm-music:/home/arm/Music
      - ./logs:/home/arm/logs
    ports:
      - "8080:8080"
    environment:
      - ARM_UID=1035
      - ARM_GID=100

volumes:
  armdata:
    driver_opts:
      type: "nfs"
      o: "addr=synologyip,nolock,soft,rw"
      device: ":/volume1/arm-data/media"
  arm-music:
    driver_opts:
      type: "nfs"
      o: "addr=synologyip,nolock,soft,rw"
      device: ":/volume1/arm-data/Music"
```

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

Using 2.6, this configuration was not an issue and I had been happily using it for about a year prior to needing to upgrade beyond 2.6

### Relevant log output

```shell
arm-rippers-1  | *** Running /etc/my_init.d/10_syslog-ng.init...
arm-rippers-1  | Sep  1 01:29:21 860e67934750 syslog-ng[12]: syslog-ng starting up; version='3.25.1'
arm-rippers-1  | *** Running /etc/my_init.d/arm_user_files_setup.sh...
arm-rippers-1  | Updating arm user id from 1000 to 1035...
arm-rippers-1  | Updating arm group id from 1000 to 100...
arm-rippers-1  | Adding arm user to 'render' group
arm-rippers-1  | Checking ownership of /home/arm
arm-rippers-1  | ---------------------------------------------
arm-rippers-1  | [ERROR]: ARM does not have permissions to /home/arm using 1035:100
arm-rippers-1  | Check your user permissions and restart ARM. Folder permissions--> 1035:1000
arm-rippers-1  | ---------------------------------------------
arm-rippers-1  | *** /etc/my_init.d/arm_user_files_setup.sh failed with status 1
arm-rippers-1  |
arm-rippers-1  | *** Killing all processes...
arm-rippers-1  | Sep  1 01:29:25 860e67934750 syslog-ng[12]: syslog-ng shutting down; version='3.25.1'
```

### Anything else?

A very related issue is #822 .  That got marked as resolved, but AFAICT the issue still persists.  I'm not a Docker expert, but I think think there might be an issue where the users aren't being created with the ARM_UID and ARM_GID, it's just doing the chmod.  I only spent about 2 minutes looking, so I could be totally wrong here though.

My version of docker does not allow me to mount sub-directories of a named volume, which is what I've got for the NFS share.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
