### ISSUE TITLE
🐛 "mounting failed" when trying to rip disks

### ISSUE THREAD

**Issue by Betonhaus** [automatic-ripping-machine/automatic-ripping-machine#1233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When I trty to rip a disk it errors out, with the logs saying "mounting failed" and "Pydvdid failed with the error: Path '/mnt/dev/sr0/VIDEO_TS' does not exist."

### To Reproduce

insert disk

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

docker compose.yml file
```
  arm-rippers:
    container_name: arm
    image: automaticrippingmachine/automatic-ripping-machine:latest
    ports:
      - 8087:8080
#    user: 1000:1002
    group_add:
      - 993
    environment:
      - ARM_UID=1000
      - ARM_GID=1002
      - UMASK=002
    volumes:
      - /mnt/docker/arm/home:/home/arm
      - /mnt/docker/arm/logs:/home/arm/logs
      - /mnt/docker/arm/config:/etc/arm/config
      - /mnt/wrk/working/automatic-ripping-machine:/home/arm/media
      - /mnt/pool/import:/home/arm/media/completed
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      - dockerbridge
    restart: unless-stopped

```

### Expected behavior?

the rip to complete

### Relevant log output

```shell
[11-07-2024 00:27:59] INFO ARM: ARM version: 2.9.0
[11-07-2024 00:27:59] INFO ARM: Python version: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
[11-07-2024 00:27:59] INFO ARM: User is: arm
[11-07-2024 00:27:59] INFO ARM: Alembic head is: b326a3663939
[11-07-2024 00:27:59] INFO ARM: Database version is: b326a3663939
[11-07-2024 00:27:59] INFO ARM: ************* Starting ARM processing at 2024-11-07 00:27:59.823921 *************
[11-07-2024 00:28:00] INFO ARM: Looking for log files older than 1 days old.
[11-07-2024 00:28:00] INFO ARM: Checking path /home/arm/logs/ for old log files...
[11-07-2024 00:28:00] INFO ARM: Checking path /home/arm/logs/progress for old log files...
[11-07-2024 00:28:00] INFO ARM: Job: V_FOR_VENDETTA
[11-07-2024 00:28:00] INFO ARM: Job #1 with PID 952 is currently running.
[11-07-2024 00:28:00] INFO ARM: Starting Disc identification
[11-07-2024 00:28:00] INFO ARM: Mounting disc to: /mnt/dev/sr0
[11-07-2024 00:28:00] ERROR ARM: Mounting failed! Rip might have problems
[11-07-2024 00:28:00] INFO ARM: Disc identified as video
[11-07-2024 00:28:00] ERROR ARM: Pydvdid failed with the error: Path '/mnt/dev/sr0/VIDEO_TS' does not exist.
[11-07-2024 00:28:02] INFO ARM: Disc title Post ident -  title:V-for-Vendetta year:2005 video_type:movie disctype: dvd
[11-07-2024 00:28:02] INFO ARM: We have no previous rips/jobs matching this label
[11-07-2024 00:28:02] INFO ARM: Waiting 60 seconds for manual override.
[11-07-2024 00:29:02] INFO ARM: ******************* Logging ARM variables *******************
[11-07-2024 00:29:02] INFO ARM: devpath: /dev/sr0
[11-07-2024 00:29:02] INFO ARM: mountpoint: /mnt/dev/sr0
[11-07-2024 00:29:02] INFO ARM: title: V-for-Vendetta
[11-07-2024 00:29:02] INFO ARM: year: 2005
[11-07-2024 00:29:02] INFO ARM: video_type: movie
[11-07-2024 00:29:02] INFO ARM: hasnicetitle: True
[11-07-2024 00:29:02] INFO ARM: label: V_FOR_VENDETTA
[11-07-2024 00:29:02] INFO ARM: disctype: dvd
[11-07-2024 00:29:02] INFO ARM: ******************* End of ARM variables *******************
[11-07-2024 00:29:02] INFO ARM: ******************* Logging config parameters *******************
[11-07-2024 00:29:02] INFO ARM: skip_transcode: False
[11-07-2024 00:29:02] INFO ARM: mainfeature: False
[11-07-2024 00:29:02] INFO ARM: minlength: 600
[11-07-2024 00:29:02] INFO ARM: maxlength: 99999
[11-07-2024 00:29:02] INFO ARM: videotype: auto
[11-07-2024 00:29:02] INFO ARM: manual_wait: True
[11-07-2024 00:29:02] INFO ARM: manual_wait_time: 60
[11-07-2024 00:29:02] INFO ARM: ripmethod: mkv
[11-07-2024 00:29:02] INFO ARM: mkv_args: 
[11-07-2024 00:29:02] INFO ARM: delrawfiles: True
[11-07-2024 00:29:02] INFO ARM: hb_preset_dvd: HQ 720p30 Surround
[11-07-2024 00:29:02] INFO ARM: hb_preset_bd: HQ 1080p30 Surround
[11-07-2024 00:29:02] INFO ARM: hb_args_dvd: --subtitle scan -F
[11-07-2024 00:29:02] INFO ARM: hb_args_bd: --subtitle scan -F --subtitle-burned --audio-lang-list eng --all-audio
[11-07-2024 00:29:02] INFO ARM: raw_path: /home/arm/media/raw/
[11-07-2024 00:29:02] INFO ARM: transcode_path: /home/arm/media/transcode/
[11-07-2024 00:29:02] INFO ARM: completed_path: /home/arm/media/completed/
[11-07-2024 00:29:02] INFO ARM: extras_sub: extras
[11-07-2024 00:29:02] INFO ARM: emby_refresh: False
[11-07-2024 00:29:02] INFO ARM: emby_server: 
[11-07-2024 00:29:02] INFO ARM: emby_port: 8096
[11-07-2024 00:29:02] INFO ARM: notify_rip: True
[11-07-2024 00:29:02] INFO ARM: notify_transcode: True
[11-07-2024 00:29:02] INFO ARM: max_concurrent_transcodes: 0
[11-07-2024 00:29:02] INFO ARM: ******************* End of config parameters *******************
[11-07-2024 00:29:02] INFO ARM: Checking for fstab entry.
[11-07-2024 00:29:02] INFO ARM: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  users,noauto,exec,utf8,ro  0  0
[11-07-2024 00:29:02] INFO ARM: Final Output directory "/home/arm/media/transcode/movies/V-for-Vendetta (2005)"
[11-07-2024 00:29:02] INFO ARM: Final Output directory "/home/arm/media/completed/movies/V-for-Vendetta (2005)"
[11-07-2024 00:29:02] INFO ARM: Processing files to: /home/arm/media/transcode/movies/V-for-Vendetta (2005)
[11-07-2024 00:29:02] INFO ARM: ************* Ripping disc with MakeMKV *************
[11-07-2024 00:29:02] INFO ARM: Updating MakeMKV key...
MakeMKV beta key for this month: T-lp4bZXFohCJOKraCftH2Z@oExMkXXEcuqsd8wNs3qjNSYf2Y1BQqIkJpxOCbBo@KTV
/home/arm/.MakeMKV/settings.conf exists, updating value of app_Key
[11-07-2024 00:29:03] INFO ARM: Starting MakeMKV rip. Method is mkv
[11-07-2024 00:29:04] ERROR ARM: Call to MakeMKV failed with code: 1 (b'')
[11-07-2024 00:29:04] ERROR ARM: MakeMKV did not complete successfully.  Exiting ARM! Error: exceptions must derive from BaseException
[11-07-2024 00:29:04] ERROR ARM: 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/makemkv.py", line 46, in makemkv
    mdisc = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'makemkvcon -r info disc:9999 | grep /dev/sr0 | grep -oP '(?<=:).*?(?=,)'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/arm_ripper.py", line 53, in rip_visual_media
    makemkv_out_path = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 53, in makemkv
    raise MakeMkvRuntimeError(mdisc_error) from mdisc_error
  File "/opt/arm/arm/ripper/makemkv.py", line 26, in __init__
    raise super().__init__(self.message)
TypeError: exceptions must derive from BaseException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 213, in <module>
    main(log_file, job, args.protection)
  File "/opt/arm/arm/ripper/main.py", line 110, in main
    arm_ripper.rip_visual_media(have_dupes, job, logfile, protection)
  File "/opt/arm/arm/ripper/arm_ripper.py", line 57, in rip_visual_media
    raise ValueError from mkv_error
ValueError
[11-07-2024 00:29:04] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
[11-07-2024 00:29:04] INFO ARM: Skipping auto eject
```

### Anything else?

Ubuntu Server 24.04 LTS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Betonhaus** [comment]
I forgot to set it to privileged, it works now.
```
  arm-rippers:
    container_name: arm-rippers
    image: automaticrippingmachine/automatic-ripping-machine:latest
    ports:
      - 8080:8080
    group_add:
      - 993 #render group
    environment:
      - ARM_UID=1000
      - ARM_GID=1002
      - UMASK=002
    privileged: true
    volumes:
      - /mnt/docker/arm/home:/home/arm
      - /mnt/docker/arm/logs:/home/arm/logs
      - /mnt/docker/arm/config:/etc/arm/config
      - /mnt/wrk/working/automatic-ripping-machine:/home/arm/media
      - /mnt/pool/import:/home/arm/media/completed
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/dri/renderD128:/dev/dri/renderD128
```
