### ISSUE TITLE
Ripper Stops after Starting Job

### ISSUE THREAD

**Issue by Waschke1994** [automatic-ripping-machine/automatic-ripping-machine#1258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The Ripper Creates a Job and stuck at this point in the Job.log
```
[12-10-2024 18:39:53] INFO ARM: Updating MakeMKV key...
MakeMKV beta key for this month: T-lp4bZXFohCJOKraCftH2Z@oExMkXXEcuqsd8wNs3qjNSYf2Y1BQqIkJpxOCbBo@KTV
/home/arm/.MakeMKV/settings.conf exists, updating value of app_Key
[12-10-2024 18:39:54] INFO ARM: Starting MakeMKV rip. Method is mkv
```
docker spams this
```
tail: cannot open '/home/arm/logs/progress/1.log' for reading: No such file or directory
```

### To Reproduce

I testet the container on several systems with ubuntu and debian... every system stuck at his point
my last test was with a user "arm" created on host (UID & GID = 1001) with this docker-compose.yml

```
services:
  app:
    container_name: arm-rippers
    privileged: true
    image: automaticrippingmachine/automatic-ripping-machine
    hostname: arm-rippers
    environment:
      ARM_UID: 1001
      ARM_GID: 1001
    ports:
      - "9090:8080"
    devices:
      - /dev/sr0:/dev/sg0
      - /dev/sr0:/dev/sg0
    volumes:
      - /home/arm/:/home/arm
      - /home/arm/Music:/home/arm/Music
      - /home/arm/logs:/home/arm/logs
      - /home/arm/media:/home/arm/media
      - /home/arm/config:/etc/arm/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    stdin_open: true
    tty: true
    restart: unless-stopped
```

i also changed the directory settings to 777 so every user can read and write... same issue

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

honestly i dont know... what I'm doing wrong ;(

### Anything else?

[One_Piece_Box_29_-_DVD_4.log](https://github.com/user-attachments/files/18083781/One_Piece_Box_29_-_DVD_4.log)
[arm.log](https://github.com/user-attachments/files/18083782/arm.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
