### ISSUE TITLE
Not CD, Blu-ray, DVD or Data. Bailing out on sr0 similar to issue 1060 different architecture.

### ISSUE THREAD

**Issue by dbhosttexas** [automatic-ripping-machine/automatic-ripping-machine#1328]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### I have checked the wiki

- [x] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [x] I'm using the latest release

### Describe the bug?

Insert DVD (pick whatever one you wish) disk spins, nothing changes in interface, Look into /home/arm/logs/arm.log and get a series of these entires...

[ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0

### To Reproduce

Install and configure arm.
insert DVD disk

### What OS are you seeing the problem on?

Other (please state in Anything else? section)

### ARM Release Version or Git hash (You can find this in the arm settings page)

2.10.5

### Expected behavior?

disk inserted, ARM starts prompts for rip and encode options.

### Relevant log output

```shell
Fri Mar  7 20:13:27 UTC 2025 Entering docker wrapper
Fri Mar  7 20:13:27 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Fri Mar  7 20:13:29 UTC 2025 Entering docker wrapper
Fri Mar  7 20:13:29 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Fri Mar  7 23:48:07 UTC 2025 Entering docker wrapper
Fri Mar  7 23:48:07 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Fri Mar  7 23:48:13 UTC 2025 Entering docker wrapper
Fri Mar  7 23:48:13 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Fri Mar  7 23:48:25 UTC 2025 Entering docker wrapper
Fri Mar  7 23:48:25 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Fri Mar  7 23:48:31 UTC 2025 Entering docker wrapper
Fri Mar  7 23:48:31 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Fri Mar  7 23:48:45 UTC 2025 Entering docker wrapper
Fri Mar  7 23:48:45 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Fri Mar  7 23:48:50 UTC 2025 Entering docker wrapper
Fri Mar  7 23:48:50 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sat Mar  8 00:03:30 UTC 2025 Entering docker wrapper
Sat Mar  8 00:03:31 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sat Mar  8 00:03:36 UTC 2025 Entering docker wrapper
Sat Mar  8 00:03:36 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
```

### Anything else?

Environment is Debian 12 AMD64 fresh load, updated and ARM installed.

Hardware.
Mainboard MSI 970A-G43 (MS-7693)
AMD FX-8370 8cores 8 threads 4ghz
32GB DDR4
Video GeForce GT710 (Default kernel modules, no Nvidia driver should I update to the Nvidia driver / module?)
1TB SATA HDD
SATA DVD/RW (I believe it is a LiteOn DVD/RW drive...)

This issue does not appear to be USB or Raspberry Pi specific as was noted in issue #1060 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by aaronm120** [comment]
Same issue here, using docker
Sat Mar  8 00:54:13 UTC 2025 Entering docker wrapper
Sat Mar  8 00:54:13 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sat Mar  8 14:29:24 UTC 2025 Entering docker wrapper
Sat Mar  8 14:29:24 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Sat Mar  8 14:44:57 UTC 2025 Entering docker wrapper
Sat Mar  8 14:44:57 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Sat Mar  8 14:46:02 UTC 2025 Entering docker wrapper
Sat Mar  8 14:46:02 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Sat Mar  8 14:46:10 UTC 2025 Entering docker wrapper
Sat Mar  8 14:46:12 UTC 2025 [ARM] sr0 has 99 Track Protection. Bailing out and ejecting.
Sat Mar  8 14:46:16 UTC 2025 Entering docker wrapper
Sat Mar  8 14:46:16 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sat Mar  8 14:46:17 UTC 2025 Entering docker wrapper
Sat Mar  8 14:46:17 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Sat Mar  8 14:47:03 UTC 2025 Entering docker wrapper
Sat Mar  8 14:47:05 UTC 2025 [ARM] sr0 has 99 Track Protection. Bailing out and ejecting.
Sat Mar  8 14:47:10 UTC 2025 Entering docker wrapper
Sat Mar  8 14:47:10 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sat Mar  8 14:47:11 UTC 2025 Entering docker wrapper
Sat Mar  8 14:47:11 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Sat Mar  8 14:47:50 UTC 2025 Entering docker wrapper
Sat Mar  8 14:47:50 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Sat Mar  8 14:48:16 UTC 2025 Entering docker wrapper
Sat Mar  8 14:48:18 UTC 2025 [ARM] sr1 has 99 Track Protection. Bailing out and ejecting.
Sat Mar  8 14:48:22 UTC 2025 Entering docker wrapper
Sat Mar  8 14:48:22 UTC 2025 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr1
Sat Mar  8 14:58:19 UTC 2025 Entering docker wrapper
Sat Mar  8 14:58:19 UTC 2025 [ARM] No

**Comment by microtechno9000** [comment]
For both users, what happens if you start a job manually, using the 'Manual Button' on the settings page
See the wiki here https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/Web-Settings-Drives#4-drive-options

**Comment by dbhosttexas** [comment]
Pops the drive open, gives me the starting message on the web app and then nothing, Following in the docker logs -f arm-rippers 

Mar  9 18:17:01 5a6ec4c767e0 CRON[15520]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
[2025-03-09 18:21:45,511] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
[2025-03-09 18:26:46,040] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
fatal: could not read Username for 'https://github.com': No such device or address
[2025-03-09 18:28:29,105] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
Mar  9 18:28:43 5a6ec4c767e0 ARM: [ARM] Entering docker wrapper
Mar  9 18:28:43 5a6ec4c767e0 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
fatal: could not read Username for 'https://github.com': No such device or address
[2025-03-09 18:28:45,579] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
Mar  9 18:29:28 5a6ec4c767e0 ARM: [ARM] Entering docker wrapper
Mar  9 18:29:28 5a6ec4c767e0 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
fatal: could not read Username for 'https://github.com': No such device or address
[2025-03-09 18:29:30,800] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
Mar  9 18:29:32 5a6ec4c767e0 ARM: [ARM] Entering docker wrapper
Mar  9 18:29:32 5a6ec4c767e0 ARM: [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
fatal: could not read Username for 'https://github.com': No such device or address
[2025-03-09 18:29:33,263] INFO ARM: settings.check_hw_transcode_support Handbrake call successful

**Comment by microtechno9000** [comment]
Odd, can you set logging to debug and try again

Also have a look in the logs folder, is it generating any logs? I am going to presume not because it isn't working

**Comment by dbhosttexas** [comment]
logs at present.

Brand new to Docker, so fishing to find out how to relaunch in debug mode.

arm@grizzly:~/logs$ docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
f77603f38459   bridge    bridge    local
e4788541c7a7   host      host      local
28775d56ee89   none      null      local
arm@grizzly:~/logs$ ls -alh
total 16K
drwxr-xr-x  3 arm arm 4.0K Mar  7 14:13 .
drwx------ 21 arm arm 4.0K Mar  8 09:03 ..
-rw-r--r--  1 arm arm 1.8K Mar  9 13:29 arm.log
drwxr-xr-x  2 arm arm 4.0K Mar  5 10:18 progress
arm@grizzly:~/logs$ ls -alh progress
total 8.0K
drwxr-xr-x 2 arm arm 4.0K Mar  5 10:18 .
drwxr-xr-x 3 arm arm 4.0K Mar  7 14:13 ..
arm@grizzly:~/logs$

**Comment by BlauDrachen** [comment]
> Brand new to Docker, so fishing to find out how to relaunch in debug mode.

Debug can be set in the arm.yaml Change the value 

LOGLEVEL: "INFO"
to
LOGLEVEL: "DEBUG"

then save and reboot your container

**Comment by BlauDrachen** [comment]
Can confirm i am having the same issue on a Proxmox LXC hosting docker which is then hosting ARM. I know USB was mentioned as a possible but unlikely cause. My drive is a USB 3 external enclosure for a sata blu-ray drive. 

I have found 3 disks which rip okay but most do not, and since i can hook the same drive into both an Ubuntu 22.04 desktop and a Windows desktop and MakeMKV detects and rips those same disks, I don't know what is going on, but I am open to suggestions and troubleshooting advice.

**Comment by microtechno9000** [comment]
How is everyone passing through drives?
If via USB that should work, but if passing physical SATA or IDE (Please upgrade) drives via KVM/QEMU there are issues there

On the settings page, if you scan for drives, do all the drives appear?

**Comment by dbhosttexas** [comment]
Bare Metal build with a SATA DVD/RW and ARM setup using Docker via the wiki instructions... 

How would KVM/QEMU have anything to do with this? I am a bit confused...

**Comment by microtechno9000** [comment]
> Bare Metal build with a SATA DVD/RW and ARM setup using Docker via the wiki instructions...
> 
> How would KVM/QEMU have anything to do with this? I am a bit confused...

If you run ARM in a VM, SATA drive pass through is possible but annoying and causes issues

Running bare metal with docker is good

**Comment by dbhosttexas** [comment]
Yes, only one drive and it comes up as Drive1 mounted at /dev/sr0

**Comment by justinParton** [comment]
The only way i have found to get past this, is to get to the container console and reinstall makemkv using the following command:  

`cd / && ./install_makemkv.sh`

Yes --- i have to do this everytime the container is started.

**Comment by panzerschrekk** [comment]
Can be solved with adding the arm user to the cdrom group: sudo usermod -a -G cdrom arm

**Comment by lizoren** [comment]
i have the same issue. i looks like 1 of my dvd drives are dead. and the other drive (lite-on something) can only read blue-ray discs.
i am on x79 i7-3930k
gtx 1050 with nvidia drivers and encoder working.
debian 12
bare metal.

**Comment by polskikrol** [comment]
There are several issues here that can happen in my experiences:
- On the host, arm needs to be a member of the cdrom and video/render (if using hardware acceleration like qsv) groups. These groups must be added to the container yml config:
```
    group_add:
      - '24'
      - '44'
      - '109'
 ```
However, the user attribute does not work at the moment and in fact it causes the instance to not start with an access issue. So, this has to instead be passed as environment var:
```
    environment:
      - ARM_UID=2002
      - ARM_GID=2002
 ```
- Devices must be passed into the container:
```
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/dri:/dev/dri
```
- If you are running privileged false, then you need to consider security items that need amendment. The SYS_ADMIN cap is needed for cdrom access and if you are using apparmor you need to use a profile that allows mount. The default profile does not allow mounting!
```
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=docker-allow_mount
```
You can search on how to dump (using apparmor_parser --dump) the default profile from apparmor. I modify this to not deny mount. Then I load it  via 'apparmor_parser -r -W <profile_name>'. Make sure to load the profile before restarting the container with a reference to it.

**Comment by eau-defemme** [comment]
Trying to get a k8s pod running and getting the same error. [I read this thread](https://www.reddit.com/r/homelab/comments/7bgtu9/a_simple_solution_for_getting_automated_ripping/) which is now 8 years old and my setup is a bit different (k3s running on a VM with USB passthrough).

Running on VM gives the same output as in the container:

```➜  ~ udevadm info --query=env "/dev/sr1"
DEVPATH=/devices/pci0000:00/0000:00:1e.0/0000:05:02.0/0000:07:1b.0/usb9/9-3/9-3:1.0/host7/target7:0:0/7:0:0:0/block/sr1
DEVNAME=/dev/sr1
DEVTYPE=disk
DISKSEQ=47
MAJOR=11
MINOR=1
SUBSYSTEM=block
USEC_INITIALIZED=177782915422
SCSI_TPGS=0
SCSI_TYPE=cd/dvd
SCSI_VENDOR=HL-DT-ST
SCSI_VENDOR_ENC=HL-DT-ST
SCSI_MODEL=BD-RE_BP60NB10
SCSI_MODEL_ENC=BD-RE\x20BP60NB10\x20\x20
SCSI_REVISION=1.00
ID_SCSI=1
ID_SCSI_INQUIRY=1
ID_VENDOR=HL-DT-ST
ID_VENDOR_ENC=HL-DT-ST
ID_MODEL=BD-RE_BP60NB10
ID_MODEL_ENC=BD-RE\x20BP60NB10\x20\x20
ID_REVISION=1.00
ID_TYPE=cd
ID_CDROM=1
SYSTEMD_MOUNT_DEVICE_BOUND=1
ID_CDROM_CD_R=1
ID_CDROM_CD_RW=1
ID_CDROM_DVD=1
ID_CDROM_DVD_R=1
ID_CDROM_DVD_RAM=1
ID_CDROM_MRW=1
ID_CDROM_MRW_W=1
ID_CDROM_BD_RE=1
ID_CDROM_BD_R_RRM=1
ID_CDROM_BD_R_SRM=1
ID_CDROM_BD=1
ID_CDROM_DVD_PLUS_R_DL=1
ID_CDROM_DVD_PLUS_R=1
ID_CDROM_DVD_PLUS_RW=1
ID_CDROM_DVD_R_DL_JR=1
ID_CDROM_DVD_R_DL_SEQ=1
ID_CDROM_DVD_RW_SEQ=1
ID_CDROM_DVD_RW_RO=1
ID_CDROM_CD=1
ID_CDROM_RW_REMOVABLE=1
ID_CDROM_DVD_RW=1
ID_CDROM_DVD_R_DL=1
ID_CDROM_BD_R=1
ID_CDROM_MEDIA=1
ID_CDROM_MEDIA_CD=1
ID_CDROM_MEDIA_SESSION_COUNT=1
ID_CDROM_MEDIA_TRACK_COUNT=22
ID_CDROM_MEDIA_TRACK_COUNT_AUDIO=22
ID_BUS=usb
ID_MODEL_ID=2571
ID_SERIAL=HL-DT-ST_BD-RE_BP60NB10_BE3000000000168A-0:0
ID_SERIAL_SHORT=BE3000000000168A
ID_VENDOR_ID=152e
ID_INSTANCE=0:0
ID_USB_MODEL=BD-RE_BP60NB10
ID_USB_MODEL_ENC=BD-RE\x20BP60NB10\x20\x20
ID_USB_MODEL_ID=2571
ID_USB_SERIAL=HL-DT-ST_BD-RE_BP60NB10_BE3000000000168A-0:0
ID_USB_SERIAL_SHORT=BE3000000000168A
ID_USB_VENDOR=HL-DT-ST
ID_USB_VENDOR_ENC=HL-DT-ST
ID_USB_VENDOR_ID=152e
ID_USB_REVISION=1.00
ID_USB_TYPE=cd
ID_USB_INSTANCE=0:0
ID_USB_INTERFACES=:080650:
ID_USB_INTERFACE_NUM=00
ID_USB_DRIVER=usb-storage
```


the YAML for the deployment if anyone needs it (WIP)
```yaml
# docker run -d \
#    -p "8080:8080" \
#    -e ARM_UID="1001" \
#    -e ARM_GID="1001" \
#    -v "/home/arm:/home/arm" \
#    -v "/home/arm/Music:/home/arm/Music" \
#    -v "/home/arm/logs:/home/arm/logs" \
#    -v "/home/arm/media:/home/arm/media" \
#    -v "/home/arm/config:/etc/arm/config" \
#    --device=/dev/sr0:/dev/sr0 \
#    --device=/dev/sr1:/dev/sr1 \
#    --device=/dev/sr2:/dev/sr2 \
#    --device=/dev/sr3:/dev/sr3 \
#    --privileged \
#    --restart "always" \
#    --name "arm-rippers" \
#    automaticrippingmachine/automatic-ripping-machine:latest
apiVersion: v1
kind: ConfigMap
metadata:
  name: arm
  namespace: fran
data:
  PUID: "1000"
  PGID: "1000"
  TIMEZONE: "America/Chicago"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arm
  namespace: fran
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: iscsi
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arm
  namespace: fran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arm
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: arm
    spec:
      securityContext:
        fsGroup: 1000
        supplementalGroups: [123,24,44,109]
      containers:
      - image: automaticrippingmachine/automatic-ripping-machine:latest
        name: arm
        env:
        # - name: ARM_UID
        #   valueFrom:
        #     configMapKeyRef:
        #       name: arm
        #       key: PUID
        # - name: ARM_GID
        #   valueFrom:
        #     configMapKeyRef:
        #       name: arm
        #       key: PGID
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /home/arm
          name: pvc
          subPath: home
        - mountPath: /etc/arm/config
          name: pvc
          subPath: config
        - mountPath: /home/arm/Music
          name: media
          subPath: music
        - mountPath: /home/arm/media
          name: media
        - mountPath: /run/udev
          readOnly: true
          name: udev
        - mountPath: /dev/sr0
          name: disc-reader-a
        - mountPath: /dev/sr1
          name: disc-reader-b
        - mountPath: /dev/sg1
          name: disc-reader-ag
        - mountPath: /dev/sg2
          name: disc-reader-bg
      restartPolicy: Always
      volumes:
      - name: media
        nfs:
          server: omega.lan.SNIP
          path: /mnt/coffers/k8s/data/media
      - name: udev
        hostPath:
          path: /run/udev
          type: Directory
      - name: pvc
        persistentVolumeClaim:
          claimName: arm
      - name: disc-reader-a
        hostPath:
          path: /dev/sr0
          type: BlockDevice
      - name: disc-reader-b
        hostPath:
          path: /dev/sr1
          type: BlockDevice
      - name: disc-reader-ag
        hostPath:
          path: /dev/sg1
      - name: disc-reader-bg
        hostPath:
          path: /dev/sg2
---
apiVersion: v1
kind: Service
metadata:
  name: arm
  namespace: fran
spec:
  ports:
    - name: webinterface
      port: 8080
  selector:
    app: arm-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arm
  namespace: fran
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entryPoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: identity-chain-authelia-auth@kubernetescrd
spec:
  tls:
  - hosts:
    - arm.SNIP
    secretName: arm
  rules:
    - host: arm.SNIP
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: arm
              port:
                number: 8080
```

Out of curiosity I've also tried using the qemu DVD drive with an ISO file mounted and that also failed, this makes me think it's not a hardware issue. However, I clearly do have udev access inside the container, so I'm not sure where the software is failing either. Any feedback or suggestions are welcome, I'm happy to provide any info needed that I may have missed.
