### ISSUE TITLE
🔧🐋 Docker compose setup

### ISSUE THREAD

**Issue by jswetzen** [automatic-ripping-machine/automatic-ripping-machine#1415]
### Is this feature missing in the latest version?

- [x] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I found the scripted docker setup pretty opaque while it also includes manual editing, and I always had some issues. I also like to use Portainer, so docker compose is my standard.

### Describe the solution you'd like?

An example compose file that's easy to use and shows the different options.

### Anything else?

I made a compose file that I think is a good starting point, you just have one place for editing paths and environment variables.

```yaml
# Common path definitions
x-arm-volumes: &arm-volumes
  - /root/arm/home:/home/arm
  - /root/arm/music:/home/arm/music
  - /root/arm/logs:/home/arm/logs
  - /root/arm/media:/home/arm/media
  - /root/arm/config:/etc/arm/config
# Common environment variables
x-arm-env: &arm-env
  ARM_UID: ${ARM_UID:-1000}
  ARM_GID: ${ARM_GID:-1000}
  TZ: ${TZ:-UTC}
  NVIDIA_DRIVER_CAPABILITIES: all
  UNIDENTIFIED_EJECT: False

services:
  arm-init:
    image: alpine:latest
    volumes: *arm-volumes
    environment: *arm-env
    command: >
      sh -c "
        echo 'Creating ARM directories...' &&
        mkdir -p /home/arm /home/arm/music /home/arm/logs /home/arm/media /etc/arm/config &&
        mkdir -p /home/arm/media/{raw,transcode,completed,movies} /home/arm/{db,.MakeMKV} &&
        echo 'Setting ownership to $${ARM_UID}:$${ARM_GID}...' &&
        chown -R $${ARM_UID}:$${ARM_GID} /home/arm /etc/arm/config &&
        echo 'ARM directories initialized successfully!'
      "

  arm:
    image: automaticrippingmachine/automatic-ripping-machine:latest
    depends_on:
      arm-init:
        condition: service_completed_successfully
    container_name: arm-ripper
    restart: always
    privileged: true
    
    ports:
      - "8080:8080"
    
    environment: *arm-env
    volumes: *arm-volumes
    
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sg7:/dev/sg7
    
    # Resource limits (optional)
    # cpuset: "2,3,4,5,6,7"
    # mem_limit: 4g
    # memswap_limit: 4g
``` 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
