### ISSUE TITLE
Setup is not permitting the creation of admin account.

### ISSUE THREAD

**Issue by IamTheCarl** [automatic-ripping-machine/automatic-ripping-machine#532]
- [ X ] I have checked the wiki
- [ X ] I have searched for similar issues

**Describe the bug**
I am using the Docker Container.
An admin account must be created to make use of ARM's most important features.
The setup page is not giving me the opportunity to do so. The documentation stated that I would have an opportunity to create an admin account on setup, but instead, it just brings me right to a login screen. 

**To Reproduce**
I followed the instructions documented here with a few exceptions: https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker

I have documented my exceptions. All of my persistent storage is in Docker volumes, so there is no need for an arm user outside of the container.
The following is from the yaml file I used to bring up the service.
```
  ripping-machine:
    container_name: ripping_machine
    image: 1337server/automatic-ripping-machine
    volumes:
      - ripping_machine_config:/etc/arm/config
      - ripping_machine_media:/home/arm/media
    ports:
      - 8080:8080
    labels: # Traefik lets me host multiple webservices through port 80. This issue persists if I don't use traefik and go through port 8080.
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.ripping-machine.rule=Host(`ripping-machine.carlcore`)
      - traefik.http.routers.ripping-machine.entrypoints=web
      - traefik.http.services.ripping-machine.loadbalancer.server.port=8080
    networks:
      - proxy
    devices:
      - "/dev/sr0:/dev/sr0"
    privileged: true
```

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"

```

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
I used the image information since I think that's what's valid here.
```
REPOSITORY                                                          TAG              IMAGE ID       CREATED         SIZE
1337server/automatic-ripping-machine                                latest           4fa1aedde10d   27 hours ago    1.57GB
```

### Log file
[arm.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/9069600/arm.log)

Hopefully, this is just a case of user error.
