### ISSUE TITLE
🐋 Doesn't Rip DVD

### ISSUE THREAD

**Issue by Swackles** [automatic-ripping-machine/automatic-ripping-machine#910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I had two issues, first was the issue that inserted DVD didn't get recognized or the disk is empty. To get around that added a 15-second sleep to [docker_arm_wrapper.sh](https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/main/scripts/docker/docker_arm_wrapper.sh) and that fixed that issue.

The second issue is that arm does nothing with the inserted disk. It detects the disk properly, then says that it's trying to write a job to logfile, and then nothing happens.

### To Reproduce

using this docker-compose

```yaml
version: '3.3'
services:
  automatic-ripping-machine:
    container_name: arm-rippers
    image: '1337server/automatic-ripping-machine:latest'
    ports:
      - '10000:8080'
    environment:
      - ARM_UID=1000
      - ARM_GID=1000
    volumes:
      - './data/home/arm:/home/arm'
      - './data/music:/home/arm/Music'
      - './logs:/home/arm/logs'
      - './data/media:/home/arm/media'
      - './config:/etc/arm/config'
    devices:
      - '/dev/sr0:/dev/sr0'
    privileged: false
    restart: always

```

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

Should start ripping DVD

### Relevant log output

```shell
[2023-08-06 13:18:36,323] INFO ARM: main.<module> Drive appears to be empty or is not ready.  Exiting ARM.
[2023-08-06 13:40:05,054] INFO ARM: main.<module> ARM is trying to write a job to the empty.log, or NAS**.log
[2023-08-06 13:44:39,263] INFO ARM: main.<module> ARM is trying to write a job to the empty.log, or NAS**.log
Sun Aug  6 14:10:29 UTC 2023 Entering docker wrapper
Sun Aug  6 14:10:29 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sun Aug  6 14:10:34 UTC 2023 Entering docker wrapper
Sun Aug  6 14:10:34 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sun Aug  6 14:10:42 UTC 2023 Entering docker wrapper
Sun Aug  6 14:10:42 UTC 2023 [ARM] Starting ARM for DVD on sr0
[2023-08-06 14:10:44,106] INFO ARM: main.<module> Drive appears to be empty or is not ready.  Exiting ARM.
Sun Aug  6 14:13:34 UTC 2023 Entering docker wrapper
Sun Aug  6 14:13:34 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sun Aug  6 14:13:53 UTC 2023 Entering docker wrapper
Sun Aug  6 14:13:53 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sun Aug  6 14:14:08 UTC 2023 Entering docker wrapper
Sun Aug  6 14:14:08 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sun Aug  6 14:17:05 UTC 2023 Entering docker wrapper
Sun Aug  6 14:17:06 UTC 2023 [ARM] Starting ARM for DVD on sr0
[2023-08-06 14:17:07,904] INFO ARM: main.<module> ARM is trying to write a job to the empty.log, or NAS**.log
Sun Aug  6 14:25:27 UTC 2023 Entering docker wrapper
Sun Aug  6 14:25:27 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sun Aug  6 14:26:01 UTC 2023 Entering docker wrapper
Sun Aug  6 14:26:01 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sun Aug  6 14:26:31 UTC 2023 Entering docker wrapper
Sun Aug  6 14:26:31 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sun Aug  6 14:27:02 UTC 2023 Entering docker wrapper
Sun Aug  6 14:27:02 UTC 2023 [ARM] Not CD, Blu-ray, DVD or Data. Bailing out on sr0
Sun Aug  6 14:53:32 UTC 2023 Entering docker wrapper
Sun Aug  6 14:53:34 UTC 2023 [ARM] Starting ARM for DVD on sr0
[2023-08-06 14:53:35,293] INFO ARM: main.<module> ARM is trying to write a job to the empty.log, or NAS**.log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
